// <auto-generated />
using System;
using FastCopy.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FastCopy.Migrations
{
    [DbContext(typeof(FastCopyDbContext))]
    [Migration("20220805070822_SetDetailModel")]
    partial class SetDetailModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("FastCopy.Models.CopyInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CopyInfo");
                });

            modelBuilder.Entity("FastCopy.Models.DetailSetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SetModelId");

                    b.ToTable("DetailSetModel");
                });

            modelBuilder.Entity("FastCopy.Models.SetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SetModel");
                });

            modelBuilder.Entity("FastCopy.Models.DetailSetModel", b =>
                {
                    b.HasOne("FastCopy.Models.SetModel", null)
                        .WithMany("DetailSetModels")
                        .HasForeignKey("SetModelId");
                });

            modelBuilder.Entity("FastCopy.Models.SetModel", b =>
                {
                    b.Navigation("DetailSetModels");
                });
#pragma warning restore 612, 618
        }
    }
}
